[2024-05-10T10:49:21.142+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:49:21.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:49:21.149+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:21.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:49:21.156+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:21.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:49:21.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:49:21.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.035 seconds
[2024-05-10T10:49:51.513+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:49:51.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:49:51.522+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:51.521+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:49:51.531+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:49:51.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:49:51.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:49:51.552+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.050 seconds
[2024-05-10T10:50:22.119+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:50:22.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:50:22.124+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:22.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:50:22.132+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:22.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:50:22.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:50:22.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.041 seconds
[2024-05-10T10:50:52.740+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:50:52.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:50:52.743+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:52.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:50:52.750+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:50:52.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:50:52.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:50:52.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.038 seconds
[2024-05-10T10:51:23.330+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:51:23.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:51:23.334+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:23.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:51:23.340+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:23.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:51:23.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:51:23.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.038 seconds
[2024-05-10T10:51:53.893+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:51:53.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:51:53.896+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:53.896+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:51:53.903+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:51:53.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:51:53.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:51:53.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.034 seconds
[2024-05-10T10:52:24.490+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:52:24.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:52:24.493+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:24.493+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:52:24.501+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:24.499+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:52:24.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:52:24.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.035 seconds
[2024-05-10T10:52:55.036+0000] {processor.py:161} INFO - Started process (PID=561) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:52:55.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:52:55.038+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:55.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:52:55.043+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:52:55.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:52:55.044+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:52:55.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.024 seconds
[2024-05-10T10:53:25.593+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:53:25.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:53:25.597+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:53:25.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:53:25.603+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:53:25.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:53:25.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:53:25.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.035 seconds
[2024-05-10T10:53:56.199+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:53:56.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:53:56.202+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:53:56.201+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:53:56.205+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:53:56.204+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:53:56.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:53:56.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.023 seconds
[2024-05-10T10:54:26.761+0000] {processor.py:161} INFO - Started process (PID=740) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:54:26.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:54:26.764+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:54:26.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:54:26.768+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:54:26.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:54:26.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:54:26.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.021 seconds
[2024-05-10T10:54:57.384+0000] {processor.py:161} INFO - Started process (PID=800) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:54:57.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:54:57.388+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:54:57.388+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:54:57.396+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:54:57.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:54:57.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:54:57.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.042 seconds
[2024-05-10T10:55:28.035+0000] {processor.py:161} INFO - Started process (PID=860) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:55:28.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:55:28.039+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:55:28.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:55:28.046+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:55:28.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:55:28.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:55:28.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.036 seconds
[2024-05-10T10:55:58.636+0000] {processor.py:161} INFO - Started process (PID=920) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:55:58.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:55:58.639+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:55:58.639+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:55:58.643+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:55:58.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:55:58.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:55:58.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.024 seconds
[2024-05-10T10:56:29.265+0000] {processor.py:161} INFO - Started process (PID=980) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:56:29.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:56:29.269+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:56:29.269+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:56:29.272+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:56:29.271+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:56:29.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:56:29.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.024 seconds
[2024-05-10T10:57:00.034+0000] {processor.py:161} INFO - Started process (PID=1040) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:00.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:57:00.039+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:57:00.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:00.047+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:57:00.045+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:57:00.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:00.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.064 seconds
[2024-05-10T10:57:16.721+0000] {processor.py:161} INFO - Started process (PID=1099) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:16.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:57:16.723+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:57:16.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:16.728+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:57:16.727+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:57:16.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:16.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.026 seconds
[2024-05-10T10:57:56.413+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:56.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:57:56.415+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:57:56.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:56.426+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:57:56.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:57:56.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:57:56.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.042 seconds
[2024-05-10T10:58:26.697+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:58:26.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:58:26.699+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:58:26.699+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:58:26.705+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:58:26.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:58:26.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:58:26.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.028 seconds
[2024-05-10T10:58:57.147+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:58:57.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:58:57.150+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:58:57.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:58:57.156+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:58:57.155+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:58:57.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:58:57.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.034 seconds
[2024-05-10T10:59:27.701+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:59:27.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:59:27.705+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:59:27.705+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:59:27.712+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:59:27.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:59:27.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:59:27.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.038 seconds
[2024-05-10T10:59:58.360+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:59:58.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T10:59:58.363+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:59:58.363+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:59:58.371+0000] {logging_mixin.py:188} INFO - [2024-05-10T10:59:58.369+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 1, in <module>
    from airflow import DAiG
ImportError: cannot import name 'DAiG' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'DAG'?
[2024-05-10T10:59:58.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T10:59:58.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.039 seconds
[2024-05-10T11:00:27.138+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:00:27.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:00:27.141+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.141+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:00:27.153+0000] {processor.py:840} INFO - DAG(s) '2_daily_transformation_analysis' retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:00:27.212+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.212+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:2_daily_transformation_analysis
[2024-05-10T11:00:27.216+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.216+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:2_daily_transformation_analysis
[2024-05-10T11:00:27.218+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.218+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:2_daily_transformation_analysis
[2024-05-10T11:00:27.218+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.218+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T11:00:27.223+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.222+0000] {dag.py:3118} INFO - Creating ORM DAG for 2_daily_transformation_analysis
[2024-05-10T11:00:27.226+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:27.226+0000] {dag.py:3954} INFO - Setting next_dagrun for 2_daily_transformation_analysis to 2020-08-01 00:00:00+00:00, run_after=2020-08-01 00:00:00+00:00
[2024-05-10T11:00:27.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.104 seconds
[2024-05-10T11:00:51.899+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:00:51.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:00:51.905+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:51.904+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:00:51.916+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:00:51.915+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:00:51.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:00:51.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.045 seconds
[2024-05-10T11:01:22.660+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:01:22.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:01:22.663+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:01:22.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:01:22.670+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:01:22.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:01:22.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:01:22.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.032 seconds
[2024-05-10T11:01:53.390+0000] {processor.py:161} INFO - Started process (PID=525) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:01:53.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:01:53.392+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:01:53.392+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:01:53.398+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:01:53.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:01:53.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:01:53.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.027 seconds
[2024-05-10T11:02:24.251+0000] {processor.py:161} INFO - Started process (PID=585) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:02:24.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:02:24.253+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:02:24.252+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:02:24.258+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:02:24.258+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:02:24.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:02:24.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.025 seconds
[2024-05-10T11:02:55.008+0000] {processor.py:161} INFO - Started process (PID=645) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:02:55.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:02:55.011+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:02:55.010+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:02:55.020+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:02:55.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:02:55.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:02:55.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.038 seconds
[2024-05-10T11:03:25.809+0000] {processor.py:161} INFO - Started process (PID=705) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:03:25.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:03:25.811+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:03:25.811+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:03:25.821+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:03:25.819+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:03:25.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:03:25.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.037 seconds
[2024-05-10T11:03:56.548+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:03:56.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:03:56.550+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:03:56.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:03:56.559+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:03:56.557+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:03:56.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:03:56.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.033 seconds
[2024-05-10T11:04:26.699+0000] {processor.py:161} INFO - Started process (PID=823) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:04:26.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:04:26.702+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:04:26.702+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:04:26.717+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:04:26.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:04:26.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:04:26.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.043 seconds
[2024-05-10T11:04:56.853+0000] {processor.py:161} INFO - Started process (PID=883) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:04:56.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:04:56.856+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:04:56.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:04:56.865+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:04:56.863+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:04:56.866+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:04:56.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.038 seconds
[2024-05-10T11:05:27.850+0000] {processor.py:161} INFO - Started process (PID=942) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:05:27.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:05:27.855+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:05:27.855+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:05:27.870+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:05:27.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:05:27.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:05:27.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.048 seconds
[2024-05-10T11:05:57.926+0000] {processor.py:161} INFO - Started process (PID=1002) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:05:57.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:05:57.929+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:05:57.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:05:57.938+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:05:57.936+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:05:57.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:05:57.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.039 seconds
[2024-05-10T11:06:28.831+0000] {processor.py:161} INFO - Started process (PID=1062) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:06:28.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:06:28.834+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:06:28.833+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:06:28.843+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:06:28.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:06:28.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:06:28.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.040 seconds
[2024-05-10T11:06:59.580+0000] {processor.py:161} INFO - Started process (PID=1122) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:06:59.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:06:59.584+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:06:59.583+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:06:59.594+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:06:59.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:06:59.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:06:59.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.040 seconds
[2024-05-10T11:07:29.893+0000] {processor.py:161} INFO - Started process (PID=1182) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:07:29.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:07:29.895+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:07:29.895+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:07:29.905+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:07:29.903+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:07:29.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:07:29.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.037 seconds
[2024-05-10T11:08:00.673+0000] {processor.py:161} INFO - Started process (PID=1242) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:08:00.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:08:00.675+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:08:00.675+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:08:00.684+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:08:00.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:08:00.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:08:00.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.039 seconds
[2024-05-10T11:08:31.387+0000] {processor.py:161} INFO - Started process (PID=1302) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:08:31.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:08:31.390+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:08:31.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:08:31.399+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:08:31.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:08:31.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:08:31.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.037 seconds
[2024-05-10T11:09:02.033+0000] {processor.py:161} INFO - Started process (PID=1362) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:09:02.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:09:02.035+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:09:02.035+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:09:02.040+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:09:02.039+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:09:02.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:09:02.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.028 seconds
[2024-05-10T11:09:32.757+0000] {processor.py:161} INFO - Started process (PID=1422) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:09:32.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:09:32.760+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:09:32.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:09:32.765+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:09:32.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:09:32.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:09:32.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.029 seconds
[2024-05-10T11:10:03.593+0000] {processor.py:161} INFO - Started process (PID=1482) to work on /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:10:03.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/transform_and_analysis.py for tasks to queue
[2024-05-10T11:10:03.595+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:10:03.595+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:10:03.604+0000] {logging_mixin.py:188} INFO - [2024-05-10T11:10:03.602+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/transform_and_analysis.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/transform_and_analysis.py", line 21, in <module>
    **os.environ
      ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-05-10T11:10:03.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/transform_and_analysis.py
[2024-05-10T11:10:03.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/transform_and_analysis.py took 0.033 seconds
